# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08852bb96380a0e5883abf954320800c1abeca2d4ec8bf5be559ac2129dcdd7e431c5842c5991bebd4909072e04035b9ade4123310690247e8994fae20ed98cf

test:
  secret_key_base: 33ebffbb7868229e1e514e44b8fee5a5013546d144731ba83485da3d42f2d190826fc612fec88dae8f8687966f4102a3279d33a0d48373ca1e16d469bd3bf3a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
